// <auto-generated />
using System;
using Avina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avina.Migrations
{
    [DbContext(typeof(AvinaDbContext))]
    [Migration("20260425121805_AddSocialFeedAndSearch")]
    partial class AddSocialFeedAndSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avina.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ExamScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Avina.Models.ContentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyViews")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploaderId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "فناوری",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آشنایی با مفاهیم پایه هوش مصنوعی و یادگیری ماشین",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/ai-intro.mp4",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 340,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "هوش مصنوعی,یادگیری ماشین",
                            ThumbnailPath = "/uploads/thumbs/ai-intro.jpg",
                            Title = "مقدمه‌ای بر هوش مصنوعی",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1520,
                            WeeklyViews = 85
                        },
                        new
                        {
                            Id = 2,
                            Category = "مهارت‌های زندگی",
                            CoinPrice = 200,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تکنیک‌های علمی برای مطالعه بهتر و به خاطر سپردن بیشتر",
                            DurationSeconds = 0,
                            FilePath = "/uploads/pdfs/study-guide.pdf",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 210,
                            PageCount = 45,
                            PurchaseCount = 0,
                            Tags = "مطالعه,یادگیری",
                            ThumbnailPath = "/uploads/thumbs/study.jpg",
                            Title = "راهنمای مطالعه مؤثر",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 890,
                            WeeklyViews = 52
                        },
                        new
                        {
                            Id = 3,
                            Category = "مهارت‌های زندگی",
                            CoinPrice = 150,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اصول و تکنیک‌های مدیریت زمان برای افراد پرمشغله",
                            DurationSeconds = 2700,
                            FilePath = "/uploads/audio/time-management.mp3",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 180,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "مدیریت زمان,بهره‌وری",
                            Title = "پادکست: مدیریت زمان",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 650,
                            WeeklyViews = 41
                        },
                        new
                        {
                            Id = 4,
                            Category = "سلامت",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "راهنمای تصویری برای داشتن تغذیه سالم و متعادل",
                            DurationSeconds = 0,
                            FilePath = "/uploads/images/healthy-food.jpg",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 520,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "تغذیه,سلامت",
                            Title = "اینفوگرافیک: تغذیه سالم",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 2100,
                            WeeklyViews = 130
                        },
                        new
                        {
                            Id = 5,
                            Category = "طراحی",
                            CoinPrice = 500,
                            CreatedAt = new DateTime(2026, 4, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آموزش کامل ابزارهای حرفه‌ای فتوشاپ",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/photoshop-pro.mp4",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 290,
                            PageCount = 0,
                            PurchaseCount = 180,
                            Tags = "فتوشاپ,طراحی گرافیک",
                            ThumbnailPath = "/uploads/thumbs/photoshop.jpg",
                            Title = "دوره فتوشاپ پیشرفته",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1230,
                            WeeklyViews = 68
                        },
                        new
                        {
                            Id = 6,
                            Category = "برنامه‌نویسی",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/css-layout.mp4",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 220,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "CSS,طراحی وب",
                            ThumbnailPath = "/uploads/thumbs/css.jpg",
                            Title = "آموزش CSS Grid و Flexbox",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 890,
                            WeeklyViews = 55
                        },
                        new
                        {
                            Id = 7,
                            Category = "علوم اجتماعی",
                            CoinPrice = 300,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/pdfs/micro-econ.pdf",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 90,
                            PageCount = 120,
                            PurchaseCount = 0,
                            Tags = "اقتصاد,دانشگاه",
                            Title = "کتاب: اصول اقتصاد خرد",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 340,
                            WeeklyViews = 22
                        },
                        new
                        {
                            Id = 8,
                            Category = "تاریخ",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 3600,
                            FilePath = "/uploads/audio/iran-history.mp3",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 310,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "ایران,تاریخ",
                            Title = "پادکست: تاریخ ایران باستان",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1200,
                            WeeklyViews = 78
                        },
                        new
                        {
                            Id = 9,
                            Category = "علوم",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/images/solar-system.jpg",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 800,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "نجوم,علوم",
                            Title = "اینفوگرافیک: سیستم شمسی",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 3200,
                            WeeklyViews = 190
                        },
                        new
                        {
                            Id = 10,
                            Category = "برنامه‌نویسی",
                            CoinPrice = 400,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/python-basics.mp4",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 530,
                            PageCount = 0,
                            PurchaseCount = 320,
                            Tags = "پایتون,کدنویسی",
                            ThumbnailPath = "/uploads/thumbs/python.jpg",
                            Title = "آموزش Python برای مبتدیان",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 2100,
                            WeeklyViews = 125
                        },
                        new
                        {
                            Id = 11,
                            Category = "زبان",
                            CoinPrice = 150,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/pdfs/english-guide.pdf",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 175,
                            PageCount = 68,
                            PurchaseCount = 95,
                            Tags = "انگلیسی,یادگیری",
                            Title = "راهنمای یادگیری زبان انگلیسی",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 670,
                            WeeklyViews = 42
                        },
                        new
                        {
                            Id = 12,
                            Category = "موسیقی",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 5400,
                            FilePath = "/uploads/audio/study-music.mp3",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 1200,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "موسیقی,مطالعه",
                            Title = "موسیقی آرامش‌بخش برای مطالعه",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 4500,
                            WeeklyViews = 290
                        },
                        new
                        {
                            Id = 13,
                            Category = "کسب و کار",
                            CoinPrice = 100,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/images/project-mgmt.jpg",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 198,
                            PageCount = 0,
                            PurchaseCount = 55,
                            Tags = "مدیریت,پروژه",
                            Title = "نقشه ذهنی: مدیریت پروژه",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 780,
                            WeeklyViews = 48
                        },
                        new
                        {
                            Id = 14,
                            Category = "برنامه‌نویسی",
                            CoinPrice = 600,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/js-advanced.mp4",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 390,
                            PageCount = 0,
                            PurchaseCount = 240,
                            Tags = "جاوااسکریپت,وب",
                            ThumbnailPath = "/uploads/thumbs/js.jpg",
                            Title = "دوره کامل JavaScript ES2024",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1560,
                            WeeklyViews = 95
                        },
                        new
                        {
                            Id = 15,
                            Category = "سلامت",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/yoga-beginner.mp4",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 700,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "یوگا,ورزش",
                            ThumbnailPath = "/uploads/thumbs/yoga.jpg",
                            Title = "تمرینات یوگا برای مبتدیان",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 2800,
                            WeeklyViews = 175
                        },
                        new
                        {
                            Id = 16,
                            Category = "ادبیات",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/pdfs/persian-stories.pdf",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 280,
                            PageCount = 85,
                            PurchaseCount = 0,
                            Tags = "داستان,ادبیات فارسی",
                            Title = "کتاب: داستان کوتاه فارسی",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1100,
                            WeeklyViews = 68
                        },
                        new
                        {
                            Id = 17,
                            Category = "کسب و کار",
                            CoinPrice = 180,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 2400,
                            FilePath = "/uploads/audio/entrepreneurship.mp3",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 230,
                            PageCount = 0,
                            PurchaseCount = 78,
                            Tags = "کارآفرینی,بیزنس",
                            Title = "پادکست: کارآفرینی در ایران",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 920,
                            WeeklyViews = 58
                        },
                        new
                        {
                            Id = 18,
                            Category = "طراحی",
                            CoinPrice = 350,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/logo-design.mp4",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 335,
                            PageCount = 0,
                            PurchaseCount = 168,
                            Tags = "فیگما,لوگو,طراحی گرافیک",
                            ThumbnailPath = "/uploads/thumbs/figma.jpg",
                            Title = "آموزش طراحی لوگو با Figma",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1340,
                            WeeklyViews = 84
                        });
                });

            modelBuilder.Entity("Avina.Models.ContentPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinSpent")
                        .HasColumnType("int");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("UserId");

                    b.ToTable("ContentPurchases");
                });

            modelBuilder.Entity("Avina.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewVideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatYouLearn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "برنامه‌نویسی",
                            CoinPrice = 800,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یادگیری پایتون از صفر تا پیشرفته با پروژه‌های واقعی",
                            DurationMinutes = 600,
                            Instructor = "علی محمدی",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "مقدماتی",
                            Price = 0m,
                            Rating = 4.7999999999999998,
                            RatingCount = 320,
                            Requirements = "هیچ پیش‌نیازی لازم نیست",
                            StudentCount = 1240,
                            Title = "دوره برنامه‌نویسی با پایتون",
                            WhatYouLearn = "مفاهیم پایه پایتون|کار با داده‌ها|پروژه‌های عملی"
                        },
                        new
                        {
                            Id = 2,
                            Category = "طراحی",
                            CoinPrice = 600,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اصول طراحی رابط کاربری و تجربه کاربری با Figma",
                            DurationMinutes = 480,
                            Instructor = "سارا کریمی",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "متوسط",
                            Price = 0m,
                            Rating = 4.5999999999999996,
                            RatingCount = 210,
                            Requirements = "آشنایی با کامپیوتر",
                            StudentCount = 856,
                            Title = "طراحی UI/UX حرفه‌ای",
                            WhatYouLearn = "اصول طراحی|کار با Figma|پروتوتایپ"
                        },
                        new
                        {
                            Id = 3,
                            Category = "کسب و کار",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "راه‌اندازی و مدیریت کسب و کار در فضای دیجیتال",
                            DurationMinutes = 300,
                            Instructor = "رضا احمدی",
                            IsFree = true,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "مقدماتی",
                            Price = 0m,
                            Rating = 4.5,
                            RatingCount = 450,
                            Requirements = "علاقه به کسب و کار",
                            StudentCount = 2100,
                            Title = "مدیریت کسب و کار دیجیتال",
                            WhatYouLearn = "استراتژی دیجیتال|بازاریابی آنلاین|مدیریت تیم"
                        },
                        new
                        {
                            Id = 4,
                            Category = "زبان",
                            CoinPrice = 500,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آموزش مکالمه و گرامر زبان انگلیسی برای زندگی روزمره",
                            DurationMinutes = 420,
                            Instructor = "مریم حسینی",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "مقدماتی",
                            Price = 0m,
                            Rating = 4.7000000000000002,
                            RatingCount = 380,
                            Requirements = "هیچ پیش‌نیازی لازم نیست",
                            StudentCount = 1680,
                            Title = "زبان انگلیسی کاربردی",
                            WhatYouLearn = "گرامر پایه|مکالمه روزمره|دستور زبان|لغات کاربردی"
                        },
                        new
                        {
                            Id = 5,
                            Category = "هنر",
                            CoinPrice = 700,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آموزش کامل نقاشی دیجیتال با Procreate و Adobe Fresco",
                            DurationMinutes = 360,
                            Instructor = "علی رضاپور",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "متوسط",
                            Price = 0m,
                            Rating = 4.9000000000000004,
                            RatingCount = 185,
                            Requirements = "آشنایی پایه با تبلت",
                            StudentCount = 920,
                            Title = "هنر نقاشی دیجیتال",
                            WhatYouLearn = "ابزارهای Procreate|تکنیک‌های رنگ‌آمیزی|طراحی کاراکتر|صادرات فایل"
                        },
                        new
                        {
                            Id = 6,
                            Category = "کسب و کار",
                            CoinPrice = 900,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "استراتژی‌های بازاریابی آنلاین، SEO و شبکه‌های اجتماعی",
                            DurationMinutes = 540,
                            Instructor = "نیلوفر کاظمی",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "متوسط",
                            Price = 0m,
                            Rating = 4.5999999999999996,
                            RatingCount = 512,
                            Requirements = "آشنایی با اینترنت",
                            StudentCount = 2340,
                            Title = "بازاریابی دیجیتال مدرن",
                            WhatYouLearn = "استراتژی محتوا|SEO و سئو|اینستاگرام مارکتینگ|تبلیغات گوگل"
                        });
                });

            modelBuilder.Entity("Avina.Models.CourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsFreePreview")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseLessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1200,
                            IsFreePreview = true,
                            Order = 1,
                            Title = "معرفی پایتون و نصب محیط"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1800,
                            IsFreePreview = true,
                            Order = 2,
                            Title = "متغیرها و انواع داده"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 2400,
                            IsFreePreview = false,
                            Order = 3,
                            Title = "شرط‌ها و حلقه‌ها"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 2100,
                            IsFreePreview = false,
                            Order = 4,
                            Title = "توابع و ماژول‌ها"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1500,
                            IsFreePreview = true,
                            Order = 1,
                            Title = "اصول اولیه طراحی"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1800,
                            IsFreePreview = true,
                            Order = 2,
                            Title = "آشنایی با Figma"
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 900,
                            IsFreePreview = true,
                            Order = 1,
                            Title = "معرفی دوره و اهداف"
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 4,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1800,
                            IsFreePreview = true,
                            Order = 2,
                            Title = "گرامر پایه: فعل To Be"
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 4,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 2100,
                            IsFreePreview = false,
                            Order = 3,
                            Title = "مکالمه روزمره: معرفی خود"
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1500,
                            IsFreePreview = true,
                            Order = 1,
                            Title = "آشنایی با Procreate"
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 5,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 2400,
                            IsFreePreview = false,
                            Order = 2,
                            Title = "لایه‌بندی و ابزارها"
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 5,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 3000,
                            IsFreePreview = false,
                            Order = 3,
                            Title = "طراحی اول کاراکتر"
                        });
                });

            modelBuilder.Entity("Avina.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PassingScore = 70,
                            TimeLimitMinutes = 30,
                            Title = "آزمون پایانی پایتون"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PassingScore = 65,
                            TimeLimitMinutes = 25,
                            Title = "آزمون UI/UX"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 4,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PassingScore = 60,
                            TimeLimitMinutes = 20,
                            Title = "آزمون زبان انگلیسی"
                        });
                });

            modelBuilder.Entity("Avina.Models.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "B",
                            ExamId = 1,
                            OptionA = "echo()",
                            OptionB = "print()",
                            OptionC = "console.log()",
                            OptionD = "write()",
                            Order = 1,
                            Points = 1,
                            QuestionText = "کدام دستور برای چاپ در پایتون استفاده می‌شود؟"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "C",
                            ExamId = 1,
                            OptionA = "function",
                            OptionB = "func",
                            OptionC = "def",
                            OptionD = "fn",
                            Order = 2,
                            Points = 1,
                            QuestionText = "در پایتون، برای تعریف یک تابع از کدام کلمه کلیدی استفاده می‌شود؟"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "D",
                            ExamId = 1,
                            OptionA = "int",
                            OptionB = "float",
                            OptionC = "bool",
                            OptionD = "str",
                            Order = 3,
                            Points = 1,
                            QuestionText = "کدام نوع داده در پایتون برای ذخیره متن استفاده می‌شود؟"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "A",
                            ExamId = 2,
                            OptionA = "User Experience",
                            OptionB = "User Extension",
                            OptionC = "Unique Experience",
                            OptionD = "Universal Exchange",
                            Order = 1,
                            Points = 1,
                            QuestionText = "UX مخفف چیست؟"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "B",
                            ExamId = 2,
                            OptionA = "Complexity",
                            OptionB = "KISS",
                            OptionC = "BOLD",
                            OptionD = "DEEP",
                            Order = 2,
                            Points = 1,
                            QuestionText = "در طراحی UI، کدام اصل به سادگی رابط کاربری اشاره دارد؟"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "B",
                            ExamId = 3,
                            OptionA = "am",
                            OptionB = "is",
                            OptionC = "are",
                            OptionD = "be",
                            Order = 1,
                            Points = 1,
                            QuestionText = "فعل 'To Be' در جمله 'She ___ a teacher' کدام است؟"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "C",
                            ExamId = 3,
                            OptionA = "شب بخیر",
                            OptionB = "عصر بخیر",
                            OptionC = "صبح بخیر",
                            OptionD = "خداحافظ",
                            Order = 2,
                            Points = 1,
                            QuestionText = "ترجمه صحیح 'Good morning' چیست؟"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "C",
                            ExamId = 3,
                            OptionA = "I am go to school",
                            OptionB = "I goes to school",
                            OptionC = "I go to school",
                            OptionD = "I going to school",
                            Order = 3,
                            Points = 1,
                            QuestionText = "کدام جمله صحیح است؟"
                        });
                });

            modelBuilder.Entity("Avina.Models.HomeBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutoEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("AutoSourceType")
                        .HasColumnType("int");

                    b.Property<int?>("AutoStrategy")
                        .HasColumnType("int");

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PrimaryLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondaryLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectionMode")
                        .HasColumnType("int");

                    b.Property<string>("Stat1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stat1Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stat2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stat2Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("HomeBanners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "🎓 مدرسه آنلاین",
                            Description = "با حل این معما ۲۰ امتیاز و ۵ کوین دریافت کن.",
                            DisplayOrder = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1600&q=80",
                            IsActive = true,
                            PrimaryLabel = "شروع ماموریت",
                            PrimaryLink = "/school",
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SecondaryLabel = "پروفایل من",
                            SecondaryLink = "/profile",
                            SelectionMode = 0,
                            Stat1 = "1.2M",
                            Stat1Label = "دانش‌آموز",
                            Stat2 = "42K",
                            Stat2Label = "دوره فعال",
                            Title = "ماموریت امروز: راز کتیبه‌های باستانی"
                        },
                        new
                        {
                            Id = 2,
                            AutoSourceType = 1,
                            AutoStrategy = 1,
                            Badge = "🔥 خودکار: برترین هفتگی",
                            Description = "",
                            DisplayOrder = 2,
                            ImageUrl = "",
                            IsActive = true,
                            PrimaryLabel = "مشاهده محتوا",
                            PrimaryLink = "/school",
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SecondaryLabel = "جزئیات",
                            SecondaryLink = "/",
                            SelectionMode = 1,
                            Title = ""
                        },
                        new
                        {
                            Id = 3,
                            Badge = "🛍️ فروشگاه",
                            Description = "محصولات فیزیکی را تهیه کن و با کد QR کوین بگیر.",
                            DisplayOrder = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1600&q=80",
                            IsActive = true,
                            PrimaryLabel = "مشاهده فروشگاه",
                            PrimaryLink = "/store",
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SecondaryLabel = "مشاهده محصولات منتخب",
                            SecondaryLink = "/store",
                            SelectionMode = 0,
                            Stat1 = "300+",
                            Stat1Label = "محصول",
                            Stat2 = "100K+",
                            Stat2Label = "کاربر فعال",
                            Title = "ابزار واقعی برای تمرین مسیر زندگی"
                        });
                });

            modelBuilder.Entity("Avina.Models.HomeFeaturedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrlOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubtitleOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOverride")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionKey", "DisplayOrder", "IsActive");

                    b.ToTable("HomeFeaturedItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "🎧 منتخب امروز",
                            DisplayOrder = 1,
                            EntityId = 12,
                            EntityType = 1,
                            IsActive = true,
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionKey = "home_curated"
                        },
                        new
                        {
                            Id = 2,
                            Badge = "🎓 کلاس ویژه",
                            DisplayOrder = 2,
                            EntityId = 1,
                            EntityType = 2,
                            IsActive = true,
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionKey = "home_curated"
                        },
                        new
                        {
                            Id = 3,
                            Badge = "🛍️ پیشنهاد فروشگاه",
                            DisplayOrder = 3,
                            EntityId = 4,
                            EntityType = 3,
                            IsActive = true,
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionKey = "home_curated"
                        });
                });

            modelBuilder.Entity("Avina.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("bit");

                    b.Property<string>("LinkLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("IsActive", "PublishAt", "ExpireAt");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "🛍️",
                            IsActive = true,
                            IsBroadcast = true,
                            LinkLabel = "مشاهده فروشگاه",
                            LinkUrl = "/store",
                            Message = "امروز تمام محصولات آموزشی فروشگاه تا ۳۰٪ تخفیف دارند.",
                            PublishAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "تخفیف ویژه فروشگاه",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Icon = "🎓",
                            IsActive = true,
                            IsBroadcast = true,
                            LinkLabel = "رفتن به مدرسه",
                            LinkUrl = "/school",
                            Message = "دوره جدید «بازاریابی دیجیتال مدرن» منتشر شد. همین حالا شروع کن.",
                            PublishAt = new DateTime(2026, 4, 18, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Title = "دوره جدید در مدرسه آنلاین",
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Icon = "⚡",
                            IsActive = true,
                            IsBroadcast = true,
                            LinkLabel = "مشاهده ماموریت",
                            LinkUrl = "/",
                            Message = "چالش امروزت فعال شد؛ با انجامش ۵۰ امتیاز و ۲۰ کوین بگیر.",
                            PublishAt = new DateTime(2026, 4, 18, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Title = "ماموریت روزانه آماده است",
                            Type = 4
                        });
                });

            modelBuilder.Entity("Avina.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreviewPages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "کتاب",
                            CoinPrice = 500,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یک کتاب جامع برای یادگیری برنامه‌نویسی از صفر",
                            FilePath = "/uploads/books/programming-intro.pdf",
                            IsActive = true,
                            IsNew = true,
                            Name = "کتاب: شروع برنامه‌نویسی",
                            PreviewPages = 2,
                            Price = 15m,
                            Stock = 9999,
                            Type = "Digital"
                        },
                        new
                        {
                            Id = 2,
                            Category = "پادکست",
                            CoinPrice = 100,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "پادکست هفتگی درباره انتخاب شغل و رشد حرفه‌ای",
                            FilePath = "/uploads/podcasts/career-guidance.mp3",
                            IsActive = true,
                            IsNew = true,
                            Name = "پادکست: مسیریابی شغلی",
                            PreviewPages = 0,
                            Price = 5m,
                            Stock = 9999,
                            Type = "Podcast"
                        },
                        new
                        {
                            Id = 3,
                            Category = "کیت مهارتی",
                            CoinPrice = 1000,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کیت فیزیکی برای یادگیری رباتیک و الکترونیک",
                            IsActive = true,
                            IsNew = true,
                            Name = "کیت مهارت: ساخت رباتیک",
                            PreviewPages = 0,
                            Price = 50m,
                            Stock = 25,
                            Type = "Physical"
                        },
                        new
                        {
                            Id = 4,
                            Category = "دوره ویدیویی",
                            CoinPrice = 800,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آموزش کامل ریاضی کنکور با تمرین‌های حل‌شده",
                            FilePath = "/uploads/videos/konkoor-math.mp4",
                            IsActive = true,
                            IsNew = true,
                            Name = "دوره ویدیویی: ریاضی کنکور",
                            PreviewPages = 0,
                            Price = 25m,
                            Stock = 9999,
                            Type = "Digital"
                        },
                        new
                        {
                            Id = 5,
                            Category = "بازی",
                            CoinPrice = 200,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "شطرنج تعاملی با ۵۰۰ پازل و آموزش استراتژی",
                            IsActive = true,
                            IsNew = false,
                            Name = "بازی فکری: شطرنج دیجیتال",
                            PreviewPages = 0,
                            Price = 8m,
                            Stock = 9999,
                            Type = "Digital"
                        },
                        new
                        {
                            Id = 6,
                            Category = "کتاب",
                            CoinPrice = 400,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کتاب فیزیک عمومی با مثال‌های حل‌شده و آزمون",
                            FilePath = "/uploads/pdfs/physics-uni.pdf",
                            IsActive = true,
                            IsNew = false,
                            Name = "کتاب: فیزیک پایه دانشگاه",
                            PreviewPages = 0,
                            Price = 12m,
                            Stock = 9999,
                            Type = "Digital"
                        },
                        new
                        {
                            Id = 7,
                            Category = "کیت مهارتی",
                            CoinPrice = 1500,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کیت ساخت ربات‌های هوشمند با آموزش برنامه‌نویسی Arduino",
                            IsActive = true,
                            IsNew = false,
                            Name = "کیت رباتیک پیشرفته",
                            PreviewPages = 0,
                            Price = 75m,
                            Stock = 20,
                            Type = "Physical"
                        },
                        new
                        {
                            Id = 8,
                            Category = "پادکست",
                            CoinPrice = 600,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "مجموعه کامل آموزش زبان انگلیسی از مقدماتی تا پیشرفته",
                            IsActive = true,
                            IsNew = false,
                            Name = "پک آموزشی زبان انگلیسی",
                            PreviewPages = 0,
                            Price = 18m,
                            Stock = 9999,
                            Type = "Digital"
                        });
                });

            modelBuilder.Entity("Avina.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Avina.Models.SocialComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "CreatedAt");

                    b.ToTable("SocialComments");
                });

            modelBuilder.Entity("Avina.Models.SocialPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SocialPosts");
                });

            modelBuilder.Entity("Avina.Models.SocialPostLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("SocialPostLikes");
                });

            modelBuilder.Entity("Avina.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Coin")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Followers")
                        .HasColumnType("int");

                    b.Property<int>("Following")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Avina.Models.UserCourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinSpent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("Avina.Models.UserExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("Avina.Models.UserNotificationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique();

                    b.ToTable("UserNotificationStates");
                });

            modelBuilder.Entity("Avina.Models.UserPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoinSpent")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPurchases");
                });

            modelBuilder.Entity("Avina.Models.Certificate", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Certificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.ContentMedia", b =>
                {
                    b.HasOne("Avina.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Avina.Models.ContentPurchase", b =>
                {
                    b.HasOne("Avina.Models.ContentMedia", "Content")
                        .WithMany("Purchases")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.CourseLesson", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Avina.Models.Exam", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Avina.Models.ExamQuestion", b =>
                {
                    b.HasOne("Avina.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Avina.Models.Notification", b =>
                {
                    b.HasOne("Avina.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Avina.Models.RefreshToken", b =>
                {
                    b.HasOne("Avina.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.SocialComment", b =>
                {
                    b.HasOne("Avina.Models.SocialPost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany("SocialComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.SocialPost", b =>
                {
                    b.HasOne("Avina.Models.User", "User")
                        .WithMany("SocialPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.SocialPostLike", b =>
                {
                    b.HasOne("Avina.Models.SocialPost", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

        b.HasOne("Avina.Models.User", "User")
            .WithMany("SocialPostLikes")
            .HasForeignKey("UserId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserCourseEnrollment", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserExamResult", b =>
                {
                    b.HasOne("Avina.Models.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserNotificationState", b =>
                {
                    b.HasOne("Avina.Models.Notification", "Notification")
                        .WithMany("UserStates")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserPurchase", b =>
                {
                    b.HasOne("Avina.Models.Product", "Product")
                        .WithMany("UserPurchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.ContentMedia", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Avina.Models.Course", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Exams");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Avina.Models.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Avina.Models.Notification", b =>
                {
                    b.Navigation("UserStates");
                });

            modelBuilder.Entity("Avina.Models.Product", b =>
                {
                    b.Navigation("UserPurchases");
                });

            modelBuilder.Entity("Avina.Models.SocialPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("Avina.Models.User", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SocialComments");

                    b.Navigation("SocialPostLikes");

                    b.Navigation("SocialPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
