// <auto-generated />
using System;
using Avina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Avina.Migrations
{
    [DbContext(typeof(AvinaDbContext))]
    [Migration("20260418192737_AddContentAndCourseSystem")]
    partial class AddContentAndCourseSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Avina.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ExamScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificateNumber")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Avina.Models.ContentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("MonthlyViews")
                        .HasColumnType("int");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UploaderId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "فناوری",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آشنایی با مفاهیم پایه هوش مصنوعی و یادگیری ماشین",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/ai-intro.mp4",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 340,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "هوش مصنوعی,یادگیری ماشین",
                            ThumbnailPath = "/uploads/thumbs/ai-intro.jpg",
                            Title = "مقدمه‌ای بر هوش مصنوعی",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1520,
                            WeeklyViews = 85
                        },
                        new
                        {
                            Id = 2,
                            Category = "مهارت‌های زندگی",
                            CoinPrice = 200,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "تکنیک‌های علمی برای مطالعه بهتر و به خاطر سپردن بیشتر",
                            DurationSeconds = 0,
                            FilePath = "/uploads/pdfs/study-guide.pdf",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 210,
                            PageCount = 45,
                            PurchaseCount = 0,
                            Tags = "مطالعه,یادگیری",
                            ThumbnailPath = "/uploads/thumbs/study.jpg",
                            Title = "راهنمای مطالعه مؤثر",
                            Type = 1,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 890,
                            WeeklyViews = 52
                        },
                        new
                        {
                            Id = 3,
                            Category = "مهارت‌های زندگی",
                            CoinPrice = 150,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اصول و تکنیک‌های مدیریت زمان برای افراد پرمشغله",
                            DurationSeconds = 2700,
                            FilePath = "/uploads/audio/time-management.mp3",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 180,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "مدیریت زمان,بهره‌وری",
                            Title = "پادکست: مدیریت زمان",
                            Type = 2,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 650,
                            WeeklyViews = 41
                        },
                        new
                        {
                            Id = 4,
                            Category = "سلامت",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "راهنمای تصویری برای داشتن تغذیه سالم و متعادل",
                            DurationSeconds = 0,
                            FilePath = "/uploads/images/healthy-food.jpg",
                            FileSizeBytes = 0L,
                            IsFree = true,
                            IsPublished = true,
                            MonthlyViews = 520,
                            PageCount = 0,
                            PurchaseCount = 0,
                            Tags = "تغذیه,سلامت",
                            Title = "اینفوگرافیک: تغذیه سالم",
                            Type = 0,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 2100,
                            WeeklyViews = 130
                        },
                        new
                        {
                            Id = 5,
                            Category = "طراحی",
                            CoinPrice = 500,
                            CreatedAt = new DateTime(2026, 4, 16, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آموزش کامل ابزارهای حرفه‌ای فتوشاپ",
                            DurationSeconds = 0,
                            FilePath = "/uploads/videos/photoshop-pro.mp4",
                            FileSizeBytes = 0L,
                            IsFree = false,
                            IsPublished = true,
                            MonthlyViews = 290,
                            PageCount = 0,
                            PurchaseCount = 180,
                            Tags = "فتوشاپ,طراحی گرافیک",
                            ThumbnailPath = "/uploads/thumbs/photoshop.jpg",
                            Title = "دوره فتوشاپ پیشرفته",
                            Type = 3,
                            UpdatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ViewCount = 1230,
                            WeeklyViews = 68
                        });
                });

            modelBuilder.Entity("Avina.Models.ContentPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinSpent")
                        .HasColumnType("int");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("UserId");

                    b.ToTable("ContentPurchases");
                });

            modelBuilder.Entity("Avina.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewVideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatYouLearn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "برنامه‌نویسی",
                            CoinPrice = 800,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یادگیری پایتون از صفر تا پیشرفته با پروژه‌های واقعی",
                            DurationMinutes = 600,
                            Instructor = "علی محمدی",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "مقدماتی",
                            Price = 0m,
                            Rating = 4.7999999999999998,
                            RatingCount = 320,
                            Requirements = "هیچ پیش‌نیازی لازم نیست",
                            StudentCount = 1240,
                            Title = "دوره برنامه‌نویسی با پایتون",
                            WhatYouLearn = "مفاهیم پایه پایتون|کار با داده‌ها|پروژه‌های عملی"
                        },
                        new
                        {
                            Id = 2,
                            Category = "طراحی",
                            CoinPrice = 600,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "اصول طراحی رابط کاربری و تجربه کاربری با Figma",
                            DurationMinutes = 480,
                            Instructor = "سارا کریمی",
                            IsFree = false,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "متوسط",
                            Price = 0m,
                            Rating = 4.5999999999999996,
                            RatingCount = 210,
                            Requirements = "آشنایی با کامپیوتر",
                            StudentCount = 856,
                            Title = "طراحی UI/UX حرفه‌ای",
                            WhatYouLearn = "اصول طراحی|کار با Figma|پروتوتایپ"
                        },
                        new
                        {
                            Id = 3,
                            Category = "کسب و کار",
                            CoinPrice = 0,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "راه‌اندازی و مدیریت کسب و کار در فضای دیجیتال",
                            DurationMinutes = 300,
                            Instructor = "رضا احمدی",
                            IsFree = true,
                            IsPublished = true,
                            Language = "فارسی",
                            Level = "مقدماتی",
                            Price = 0m,
                            Rating = 4.5,
                            RatingCount = 450,
                            Requirements = "علاقه به کسب و کار",
                            StudentCount = 2100,
                            Title = "مدیریت کسب و کار دیجیتال",
                            WhatYouLearn = "استراتژی دیجیتال|بازاریابی آنلاین|مدیریت تیم"
                        });
                });

            modelBuilder.Entity("Avina.Models.CourseLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsFreePreview")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseLessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1200,
                            IsFreePreview = true,
                            Order = 1,
                            Title = "معرفی پایتون و نصب محیط"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1800,
                            IsFreePreview = true,
                            Order = 2,
                            Title = "متغیرها و انواع داده"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 2400,
                            IsFreePreview = false,
                            Order = 3,
                            Title = "شرط‌ها و حلقه‌ها"
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 2100,
                            IsFreePreview = false,
                            Order = 4,
                            Title = "توابع و ماژول‌ها"
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1500,
                            IsFreePreview = true,
                            Order = 1,
                            Title = "اصول اولیه طراحی"
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationSeconds = 1800,
                            IsFreePreview = true,
                            Order = 2,
                            Title = "آشنایی با Figma"
                        });
                });

            modelBuilder.Entity("Avina.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PassingScore = 70,
                            TimeLimitMinutes = 30,
                            Title = "آزمون پایانی پایتون"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PassingScore = 65,
                            TimeLimitMinutes = 25,
                            Title = "آزمون UI/UX"
                        });
                });

            modelBuilder.Entity("Avina.Models.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "B",
                            ExamId = 1,
                            OptionA = "echo()",
                            OptionB = "print()",
                            OptionC = "console.log()",
                            OptionD = "write()",
                            Order = 1,
                            Points = 1,
                            QuestionText = "کدام دستور برای چاپ در پایتون استفاده می‌شود؟"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "C",
                            ExamId = 1,
                            OptionA = "function",
                            OptionB = "func",
                            OptionC = "def",
                            OptionD = "fn",
                            Order = 2,
                            Points = 1,
                            QuestionText = "در پایتون، برای تعریف یک تابع از کدام کلمه کلیدی استفاده می‌شود؟"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "D",
                            ExamId = 1,
                            OptionA = "int",
                            OptionB = "float",
                            OptionC = "bool",
                            OptionD = "str",
                            Order = 3,
                            Points = 1,
                            QuestionText = "کدام نوع داده در پایتون برای ذخیره متن استفاده می‌شود؟"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "A",
                            ExamId = 2,
                            OptionA = "User Experience",
                            OptionB = "User Extension",
                            OptionC = "Unique Experience",
                            OptionD = "Universal Exchange",
                            Order = 1,
                            Points = 1,
                            QuestionText = "UX مخفف چیست؟"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "B",
                            ExamId = 2,
                            OptionA = "Complexity",
                            OptionB = "KISS",
                            OptionC = "BOLD",
                            OptionD = "DEEP",
                            Order = 2,
                            Points = 1,
                            QuestionText = "در طراحی UI، کدام اصل به سادگی رابط کاربری اشاره دارد؟"
                        });
                });

            modelBuilder.Entity("Avina.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreviewPages")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "کتاب",
                            CoinPrice = 500,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "یک کتاب جامع برای یادگیری برنامه‌نویسی از صفر",
                            FilePath = "/uploads/books/programming-intro.pdf",
                            IsActive = true,
                            IsNew = true,
                            Name = "کتاب: شروع برنامه‌نویسی",
                            PreviewPages = 2,
                            Price = 15m,
                            Stock = 9999,
                            Type = "Digital"
                        },
                        new
                        {
                            Id = 2,
                            Category = "پادکست",
                            CoinPrice = 100,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "پادکست هفتگی درباره انتخاب شغل و رشد حرفه‌ای",
                            FilePath = "/uploads/podcasts/career-guidance.mp3",
                            IsActive = true,
                            IsNew = true,
                            Name = "پادکست: مسیریابی شغلی",
                            PreviewPages = 0,
                            Price = 5m,
                            Stock = 9999,
                            Type = "Podcast"
                        },
                        new
                        {
                            Id = 3,
                            Category = "کیت مهارتی",
                            CoinPrice = 1000,
                            CreatedAt = new DateTime(2026, 4, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "کیت فیزیکی برای یادگیری رباتیک و الکترونیک",
                            IsActive = true,
                            IsNew = true,
                            Name = "کیت مهارت: ساخت رباتیک",
                            PreviewPages = 0,
                            Price = 50m,
                            Stock = 25,
                            Type = "Physical"
                        });
                });

            modelBuilder.Entity("Avina.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Avina.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Achievements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Coin")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("Followers")
                        .HasColumnType("int");

                    b.Property<int>("Following")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Avina.Models.UserCourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinSpent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("Avina.Models.UserExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("Avina.Models.UserPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoinSpent")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPurchases");
                });

            modelBuilder.Entity("Avina.Models.Certificate", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Certificates")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.ContentMedia", b =>
                {
                    b.HasOne("Avina.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Avina.Models.ContentPurchase", b =>
                {
                    b.HasOne("Avina.Models.ContentMedia", "Content")
                        .WithMany("Purchases")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.CourseLesson", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Avina.Models.Exam", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Avina.Models.ExamQuestion", b =>
                {
                    b.HasOne("Avina.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Avina.Models.RefreshToken", b =>
                {
                    b.HasOne("Avina.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserCourseEnrollment", b =>
                {
                    b.HasOne("Avina.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserExamResult", b =>
                {
                    b.HasOne("Avina.Models.Exam", "Exam")
                        .WithMany("Results")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.UserPurchase", b =>
                {
                    b.HasOne("Avina.Models.Product", "Product")
                        .WithMany("UserPurchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Avina.Models.User", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Avina.Models.ContentMedia", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Avina.Models.Course", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("Exams");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Avina.Models.Exam", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Avina.Models.Product", b =>
                {
                    b.Navigation("UserPurchases");
                });

            modelBuilder.Entity("Avina.Models.User", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
